# This file was auto-generated by Fern from our API Definition.

import typing

FerryProgramTodoCreateRequestStatus = typing.Union[
    typing.Literal["not_started", "in_progress", "completed", "blocked"], typing.Any
]
