# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.public_ticket_response import PublicTicketResponse
from ..types.ticket_pipeline_schema import TicketPipelineSchema
from ..types.ticket_schema import TicketSchema
from .raw_client import AsyncRawTicketsClient, RawTicketsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TicketsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTicketsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTicketsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTicketsClient
        """
        return self._raw_client

    def api_routers_v_1_tickets_public_api_list_public_tickets(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TicketSchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TicketSchema]
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_list_public_tickets()
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_list_public_tickets(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_tickets_public_api_create_public_ticket(
        self,
        *,
        external_id: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        priority: typing.Optional[str] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        stage_key: typing.Optional[str] = OMIT,
        resolution_due_at: typing.Optional[dt.datetime] = OMIT,
        first_response_due_at: typing.Optional[dt.datetime] = OMIT,
        owner_id: typing.Optional[str] = OMIT,
        deal_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        external_id : typing.Optional[str]

        title : typing.Optional[str]

        description : typing.Optional[str]

        status : typing.Optional[str]

        priority : typing.Optional[str]

        visibility : typing.Optional[str]

        stage_key : typing.Optional[str]

        resolution_due_at : typing.Optional[dt.datetime]

        first_response_due_at : typing.Optional[dt.datetime]

        owner_id : typing.Optional[str]

        deal_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_create_public_ticket()
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_create_public_ticket(
            external_id=external_id,
            title=title,
            description=description,
            status=status,
            priority=priority,
            visibility=visibility,
            stage_key=stage_key,
            resolution_due_at=resolution_due_at,
            first_response_due_at=first_response_due_at,
            owner_id=owner_id,
            deal_ids=deal_ids,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_tickets_public_api_list_public_ticket_pipelines(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TicketPipelineSchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TicketPipelineSchema]
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_list_public_ticket_pipelines()
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_list_public_ticket_pipelines(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_tickets_public_api_get_public_ticket(
        self,
        ticket_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TicketSchema:
        """
        Parameters
        ----------
        ticket_id : str

        workspace_id : typing.Optional[str]

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TicketSchema
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_get_public_ticket(
            ticket_id="ticket_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_get_public_ticket(
            ticket_id, workspace_id=workspace_id, external_id=external_id, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_tickets_public_api_update_public_ticket(
        self,
        ticket_id: str,
        *,
        external_id: typing.Optional[str] = None,
        public_ticket_request_external_id: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        priority: typing.Optional[str] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        stage_key: typing.Optional[str] = OMIT,
        resolution_due_at: typing.Optional[dt.datetime] = OMIT,
        first_response_due_at: typing.Optional[dt.datetime] = OMIT,
        owner_id: typing.Optional[str] = OMIT,
        deal_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        ticket_id : str

        external_id : typing.Optional[str]

        public_ticket_request_external_id : typing.Optional[str]

        title : typing.Optional[str]

        description : typing.Optional[str]

        status : typing.Optional[str]

        priority : typing.Optional[str]

        visibility : typing.Optional[str]

        stage_key : typing.Optional[str]

        resolution_due_at : typing.Optional[dt.datetime]

        first_response_due_at : typing.Optional[dt.datetime]

        owner_id : typing.Optional[str]

        deal_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_update_public_ticket(
            ticket_id="ticket_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_update_public_ticket(
            ticket_id,
            external_id=external_id,
            public_ticket_request_external_id=public_ticket_request_external_id,
            title=title,
            description=description,
            status=status,
            priority=priority,
            visibility=visibility,
            stage_key=stage_key,
            resolution_due_at=resolution_due_at,
            first_response_due_at=first_response_due_at,
            owner_id=owner_id,
            deal_ids=deal_ids,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_tickets_public_api_delete_public_ticket(
        self,
        ticket_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        ticket_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_delete_public_ticket(
            ticket_id="ticket_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_delete_public_ticket(
            ticket_id, external_id=external_id, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_tickets_public_api_update_public_ticket_status(
        self,
        ticket_id: str,
        *,
        stage_key: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        ticket_id : str

        stage_key : typing.Optional[str]

        status : typing.Optional[str]

        external_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.tickets.api_routers_v_1_tickets_public_api_update_public_ticket_status(
            ticket_id="ticket_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_tickets_public_api_update_public_ticket_status(
            ticket_id,
            stage_key=stage_key,
            status=status,
            external_id=external_id,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data


class AsyncTicketsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTicketsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTicketsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTicketsClient
        """
        return self._raw_client

    async def api_routers_v_1_tickets_public_api_list_public_tickets(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TicketSchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TicketSchema]
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_list_public_tickets()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_list_public_tickets(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_tickets_public_api_create_public_ticket(
        self,
        *,
        external_id: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        priority: typing.Optional[str] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        stage_key: typing.Optional[str] = OMIT,
        resolution_due_at: typing.Optional[dt.datetime] = OMIT,
        first_response_due_at: typing.Optional[dt.datetime] = OMIT,
        owner_id: typing.Optional[str] = OMIT,
        deal_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        external_id : typing.Optional[str]

        title : typing.Optional[str]

        description : typing.Optional[str]

        status : typing.Optional[str]

        priority : typing.Optional[str]

        visibility : typing.Optional[str]

        stage_key : typing.Optional[str]

        resolution_due_at : typing.Optional[dt.datetime]

        first_response_due_at : typing.Optional[dt.datetime]

        owner_id : typing.Optional[str]

        deal_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_create_public_ticket()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_create_public_ticket(
            external_id=external_id,
            title=title,
            description=description,
            status=status,
            priority=priority,
            visibility=visibility,
            stage_key=stage_key,
            resolution_due_at=resolution_due_at,
            first_response_due_at=first_response_due_at,
            owner_id=owner_id,
            deal_ids=deal_ids,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_tickets_public_api_list_public_ticket_pipelines(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TicketPipelineSchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TicketPipelineSchema]
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_list_public_ticket_pipelines()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_list_public_ticket_pipelines(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_tickets_public_api_get_public_ticket(
        self,
        ticket_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TicketSchema:
        """
        Parameters
        ----------
        ticket_id : str

        workspace_id : typing.Optional[str]

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TicketSchema
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_get_public_ticket(
                ticket_id="ticket_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_get_public_ticket(
            ticket_id, workspace_id=workspace_id, external_id=external_id, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_tickets_public_api_update_public_ticket(
        self,
        ticket_id: str,
        *,
        external_id: typing.Optional[str] = None,
        public_ticket_request_external_id: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        priority: typing.Optional[str] = OMIT,
        visibility: typing.Optional[str] = OMIT,
        stage_key: typing.Optional[str] = OMIT,
        resolution_due_at: typing.Optional[dt.datetime] = OMIT,
        first_response_due_at: typing.Optional[dt.datetime] = OMIT,
        owner_id: typing.Optional[str] = OMIT,
        deal_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        ticket_id : str

        external_id : typing.Optional[str]

        public_ticket_request_external_id : typing.Optional[str]

        title : typing.Optional[str]

        description : typing.Optional[str]

        status : typing.Optional[str]

        priority : typing.Optional[str]

        visibility : typing.Optional[str]

        stage_key : typing.Optional[str]

        resolution_due_at : typing.Optional[dt.datetime]

        first_response_due_at : typing.Optional[dt.datetime]

        owner_id : typing.Optional[str]

        deal_ids : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_update_public_ticket(
                ticket_id="ticket_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_update_public_ticket(
            ticket_id,
            external_id=external_id,
            public_ticket_request_external_id=public_ticket_request_external_id,
            title=title,
            description=description,
            status=status,
            priority=priority,
            visibility=visibility,
            stage_key=stage_key,
            resolution_due_at=resolution_due_at,
            first_response_due_at=first_response_due_at,
            owner_id=owner_id,
            deal_ids=deal_ids,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_tickets_public_api_delete_public_ticket(
        self,
        ticket_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        ticket_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_delete_public_ticket(
                ticket_id="ticket_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_delete_public_ticket(
            ticket_id, external_id=external_id, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_tickets_public_api_update_public_ticket_status(
        self,
        ticket_id: str,
        *,
        stage_key: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        external_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicTicketResponse:
        """
        Parameters
        ----------
        ticket_id : str

        stage_key : typing.Optional[str]

        status : typing.Optional[str]

        external_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicTicketResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tickets.api_routers_v_1_tickets_public_api_update_public_ticket_status(
                ticket_id="ticket_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_tickets_public_api_update_public_ticket_status(
            ticket_id,
            stage_key=stage_key,
            status=status,
            external_id=external_id,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data
