# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.public_inventory_response import PublicInventoryResponse
from ..types.shop_turbo_inventory_schema import ShopTurboInventorySchema
from .raw_client import AsyncRawInventoriesClient, RawInventoriesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InventoriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInventoriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInventoriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInventoriesClient
        """
        return self._raw_client

    def api_routers_v_1_inventories_public_api_list_workspace_inventories(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ShopTurboInventorySchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ShopTurboInventorySchema]
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.inventories.api_routers_v_1_inventories_public_api_list_workspace_inventories()
        """
        _response = self._raw_client.api_routers_v_1_inventories_public_api_list_workspace_inventories(
            workspace_id=workspace_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_inventories_public_api_create_public_inventory(
        self,
        *,
        external_id: str,
        name: typing.Optional[str] = OMIT,
        item_id: typing.Optional[str] = OMIT,
        item_external_id: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        unit_price: typing.Optional[float] = OMIT,
        initial_value: typing.Optional[int] = OMIT,
        date: typing.Optional[str] = OMIT,
        warehouse_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicInventoryResponse:
        """
        Parameters
        ----------
        external_id : str

        name : typing.Optional[str]

        item_id : typing.Optional[str]

        item_external_id : typing.Optional[str]

        status : typing.Optional[str]

        inventory_status : typing.Optional[str]

        currency : typing.Optional[str]

        unit_price : typing.Optional[float]

        initial_value : typing.Optional[int]

        date : typing.Optional[str]

        warehouse_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicInventoryResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.inventories.api_routers_v_1_inventories_public_api_create_public_inventory(
            external_id="externalId",
        )
        """
        _response = self._raw_client.api_routers_v_1_inventories_public_api_create_public_inventory(
            external_id=external_id,
            name=name,
            item_id=item_id,
            item_external_id=item_external_id,
            status=status,
            inventory_status=inventory_status,
            currency=currency,
            unit_price=unit_price,
            initial_value=initial_value,
            date=date,
            warehouse_id=warehouse_id,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_inventories_public_api_get_public_inventory(
        self,
        inventory_id: str,
        *,
        external_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ShopTurboInventorySchema:
        """
        Parameters
        ----------
        inventory_id : str

        external_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShopTurboInventorySchema
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.inventories.api_routers_v_1_inventories_public_api_get_public_inventory(
            inventory_id="inventory_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_inventories_public_api_get_public_inventory(
            inventory_id, external_id=external_id, accept_language=accept_language, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_inventories_public_api_update_public_inventory(
        self,
        inventory_id: str,
        *,
        external_id: str,
        name: typing.Optional[str] = OMIT,
        item_id: typing.Optional[str] = OMIT,
        item_external_id: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        unit_price: typing.Optional[float] = OMIT,
        initial_value: typing.Optional[int] = OMIT,
        date: typing.Optional[str] = OMIT,
        warehouse_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicInventoryResponse:
        """
        Parameters
        ----------
        inventory_id : str

        external_id : str

        name : typing.Optional[str]

        item_id : typing.Optional[str]

        item_external_id : typing.Optional[str]

        status : typing.Optional[str]

        inventory_status : typing.Optional[str]

        currency : typing.Optional[str]

        unit_price : typing.Optional[float]

        initial_value : typing.Optional[int]

        date : typing.Optional[str]

        warehouse_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicInventoryResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.inventories.api_routers_v_1_inventories_public_api_update_public_inventory(
            inventory_id="inventory_id",
            external_id="externalId",
        )
        """
        _response = self._raw_client.api_routers_v_1_inventories_public_api_update_public_inventory(
            inventory_id,
            external_id=external_id,
            name=name,
            item_id=item_id,
            item_external_id=item_external_id,
            status=status,
            inventory_status=inventory_status,
            currency=currency,
            unit_price=unit_price,
            initial_value=initial_value,
            date=date,
            warehouse_id=warehouse_id,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_inventories_public_api_delete_public_inventory(
        self,
        inventory_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicInventoryResponse:
        """
        Parameters
        ----------
        inventory_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicInventoryResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.inventories.api_routers_v_1_inventories_public_api_delete_public_inventory(
            inventory_id="inventory_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_inventories_public_api_delete_public_inventory(
            inventory_id, external_id=external_id, request_options=request_options
        )
        return _response.data


class AsyncInventoriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInventoriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInventoriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInventoriesClient
        """
        return self._raw_client

    async def api_routers_v_1_inventories_public_api_list_workspace_inventories(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ShopTurboInventorySchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ShopTurboInventorySchema]
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.inventories.api_routers_v_1_inventories_public_api_list_workspace_inventories()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_inventories_public_api_list_workspace_inventories(
            workspace_id=workspace_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_inventories_public_api_create_public_inventory(
        self,
        *,
        external_id: str,
        name: typing.Optional[str] = OMIT,
        item_id: typing.Optional[str] = OMIT,
        item_external_id: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        unit_price: typing.Optional[float] = OMIT,
        initial_value: typing.Optional[int] = OMIT,
        date: typing.Optional[str] = OMIT,
        warehouse_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicInventoryResponse:
        """
        Parameters
        ----------
        external_id : str

        name : typing.Optional[str]

        item_id : typing.Optional[str]

        item_external_id : typing.Optional[str]

        status : typing.Optional[str]

        inventory_status : typing.Optional[str]

        currency : typing.Optional[str]

        unit_price : typing.Optional[float]

        initial_value : typing.Optional[int]

        date : typing.Optional[str]

        warehouse_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicInventoryResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.inventories.api_routers_v_1_inventories_public_api_create_public_inventory(
                external_id="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_inventories_public_api_create_public_inventory(
            external_id=external_id,
            name=name,
            item_id=item_id,
            item_external_id=item_external_id,
            status=status,
            inventory_status=inventory_status,
            currency=currency,
            unit_price=unit_price,
            initial_value=initial_value,
            date=date,
            warehouse_id=warehouse_id,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_inventories_public_api_get_public_inventory(
        self,
        inventory_id: str,
        *,
        external_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ShopTurboInventorySchema:
        """
        Parameters
        ----------
        inventory_id : str

        external_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShopTurboInventorySchema
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.inventories.api_routers_v_1_inventories_public_api_get_public_inventory(
                inventory_id="inventory_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_inventories_public_api_get_public_inventory(
            inventory_id, external_id=external_id, accept_language=accept_language, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_inventories_public_api_update_public_inventory(
        self,
        inventory_id: str,
        *,
        external_id: str,
        name: typing.Optional[str] = OMIT,
        item_id: typing.Optional[str] = OMIT,
        item_external_id: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        unit_price: typing.Optional[float] = OMIT,
        initial_value: typing.Optional[int] = OMIT,
        date: typing.Optional[str] = OMIT,
        warehouse_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicInventoryResponse:
        """
        Parameters
        ----------
        inventory_id : str

        external_id : str

        name : typing.Optional[str]

        item_id : typing.Optional[str]

        item_external_id : typing.Optional[str]

        status : typing.Optional[str]

        inventory_status : typing.Optional[str]

        currency : typing.Optional[str]

        unit_price : typing.Optional[float]

        initial_value : typing.Optional[int]

        date : typing.Optional[str]

        warehouse_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicInventoryResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.inventories.api_routers_v_1_inventories_public_api_update_public_inventory(
                inventory_id="inventory_id",
                external_id="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_inventories_public_api_update_public_inventory(
            inventory_id,
            external_id=external_id,
            name=name,
            item_id=item_id,
            item_external_id=item_external_id,
            status=status,
            inventory_status=inventory_status,
            currency=currency,
            unit_price=unit_price,
            initial_value=initial_value,
            date=date,
            warehouse_id=warehouse_id,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_inventories_public_api_delete_public_inventory(
        self,
        inventory_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicInventoryResponse:
        """
        Parameters
        ----------
        inventory_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicInventoryResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.inventories.api_routers_v_1_inventories_public_api_delete_public_inventory(
                inventory_id="inventory_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_inventories_public_api_delete_public_inventory(
            inventory_id, external_id=external_id, request_options=request_options
        )
        return _response.data
