# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..types.inventory_transaction_schema import InventoryTransactionSchema
from ..types.public_inventory_transaction_response import PublicInventoryTransactionResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawInventoryTransactionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def api_routers_v_1_inventory_transactions_public_api_list_workspace_inventory_transactions(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[InventoryTransactionSchema]]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[InventoryTransactionSchema]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/public/inventory-transactions",
            method="GET",
            params={
                "workspace_id": workspace_id,
                "lang": lang,
                "language": language,
            },
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[InventoryTransactionSchema],
                    construct_type(
                        type_=typing.List[InventoryTransactionSchema],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_routers_v_1_inventory_transactions_public_api_create_public_inventory_transaction(
        self,
        *,
        transaction_type: str,
        inventory_id: typing.Optional[str] = OMIT,
        inventory_external_id: typing.Optional[str] = OMIT,
        amount: typing.Optional[int] = OMIT,
        transaction_amount: typing.Optional[int] = OMIT,
        transaction_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_type: typing.Optional[str] = OMIT,
        use_unit_value: typing.Optional[bool] = OMIT,
        price: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PublicInventoryTransactionResponse]:
        """
        Parameters
        ----------
        transaction_type : str

        inventory_id : typing.Optional[str]

        inventory_external_id : typing.Optional[str]

        amount : typing.Optional[int]

        transaction_amount : typing.Optional[int]

        transaction_date : typing.Optional[str]

        status : typing.Optional[str]

        inventory_type : typing.Optional[str]

        use_unit_value : typing.Optional[bool]

        price : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PublicInventoryTransactionResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/public/inventory-transactions",
            method="POST",
            json={
                "inventoryId": inventory_id,
                "inventoryExternalId": inventory_external_id,
                "transactionType": transaction_type,
                "amount": amount,
                "transactionAmount": transaction_amount,
                "transactionDate": transaction_date,
                "status": status,
                "inventoryType": inventory_type,
                "useUnitValue": use_unit_value,
                "price": price,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PublicInventoryTransactionResponse,
                    construct_type(
                        type_=PublicInventoryTransactionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_routers_v_1_inventory_transactions_public_api_get_public_inventory_transaction(
        self,
        transaction_id: str,
        *,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[InventoryTransactionSchema]:
        """
        Parameters
        ----------
        transaction_id : str

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[InventoryTransactionSchema]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/public/inventory-transactions/{jsonable_encoder(transaction_id)}",
            method="GET",
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InventoryTransactionSchema,
                    construct_type(
                        type_=InventoryTransactionSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_routers_v_1_inventory_transactions_public_api_update_public_inventory_transaction(
        self,
        transaction_id: str,
        *,
        transaction_type: str,
        inventory_id: typing.Optional[str] = OMIT,
        inventory_external_id: typing.Optional[str] = OMIT,
        amount: typing.Optional[int] = OMIT,
        transaction_amount: typing.Optional[int] = OMIT,
        transaction_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_type: typing.Optional[str] = OMIT,
        use_unit_value: typing.Optional[bool] = OMIT,
        price: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PublicInventoryTransactionResponse]:
        """
        Parameters
        ----------
        transaction_id : str

        transaction_type : str

        inventory_id : typing.Optional[str]

        inventory_external_id : typing.Optional[str]

        amount : typing.Optional[int]

        transaction_amount : typing.Optional[int]

        transaction_date : typing.Optional[str]

        status : typing.Optional[str]

        inventory_type : typing.Optional[str]

        use_unit_value : typing.Optional[bool]

        price : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PublicInventoryTransactionResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/public/inventory-transactions/{jsonable_encoder(transaction_id)}",
            method="PUT",
            json={
                "inventoryId": inventory_id,
                "inventoryExternalId": inventory_external_id,
                "transactionType": transaction_type,
                "amount": amount,
                "transactionAmount": transaction_amount,
                "transactionDate": transaction_date,
                "status": status,
                "inventoryType": inventory_type,
                "useUnitValue": use_unit_value,
                "price": price,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PublicInventoryTransactionResponse,
                    construct_type(
                        type_=PublicInventoryTransactionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def api_routers_v_1_inventory_transactions_public_api_delete_public_inventory_transaction(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PublicInventoryTransactionResponse]:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PublicInventoryTransactionResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/public/inventory-transactions/{jsonable_encoder(transaction_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PublicInventoryTransactionResponse,
                    construct_type(
                        type_=PublicInventoryTransactionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawInventoryTransactionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def api_routers_v_1_inventory_transactions_public_api_list_workspace_inventory_transactions(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[InventoryTransactionSchema]]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[InventoryTransactionSchema]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/public/inventory-transactions",
            method="GET",
            params={
                "workspace_id": workspace_id,
                "lang": lang,
                "language": language,
            },
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[InventoryTransactionSchema],
                    construct_type(
                        type_=typing.List[InventoryTransactionSchema],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_routers_v_1_inventory_transactions_public_api_create_public_inventory_transaction(
        self,
        *,
        transaction_type: str,
        inventory_id: typing.Optional[str] = OMIT,
        inventory_external_id: typing.Optional[str] = OMIT,
        amount: typing.Optional[int] = OMIT,
        transaction_amount: typing.Optional[int] = OMIT,
        transaction_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_type: typing.Optional[str] = OMIT,
        use_unit_value: typing.Optional[bool] = OMIT,
        price: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PublicInventoryTransactionResponse]:
        """
        Parameters
        ----------
        transaction_type : str

        inventory_id : typing.Optional[str]

        inventory_external_id : typing.Optional[str]

        amount : typing.Optional[int]

        transaction_amount : typing.Optional[int]

        transaction_date : typing.Optional[str]

        status : typing.Optional[str]

        inventory_type : typing.Optional[str]

        use_unit_value : typing.Optional[bool]

        price : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PublicInventoryTransactionResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/public/inventory-transactions",
            method="POST",
            json={
                "inventoryId": inventory_id,
                "inventoryExternalId": inventory_external_id,
                "transactionType": transaction_type,
                "amount": amount,
                "transactionAmount": transaction_amount,
                "transactionDate": transaction_date,
                "status": status,
                "inventoryType": inventory_type,
                "useUnitValue": use_unit_value,
                "price": price,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PublicInventoryTransactionResponse,
                    construct_type(
                        type_=PublicInventoryTransactionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_routers_v_1_inventory_transactions_public_api_get_public_inventory_transaction(
        self,
        transaction_id: str,
        *,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[InventoryTransactionSchema]:
        """
        Parameters
        ----------
        transaction_id : str

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[InventoryTransactionSchema]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/public/inventory-transactions/{jsonable_encoder(transaction_id)}",
            method="GET",
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InventoryTransactionSchema,
                    construct_type(
                        type_=InventoryTransactionSchema,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_routers_v_1_inventory_transactions_public_api_update_public_inventory_transaction(
        self,
        transaction_id: str,
        *,
        transaction_type: str,
        inventory_id: typing.Optional[str] = OMIT,
        inventory_external_id: typing.Optional[str] = OMIT,
        amount: typing.Optional[int] = OMIT,
        transaction_amount: typing.Optional[int] = OMIT,
        transaction_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        inventory_type: typing.Optional[str] = OMIT,
        use_unit_value: typing.Optional[bool] = OMIT,
        price: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PublicInventoryTransactionResponse]:
        """
        Parameters
        ----------
        transaction_id : str

        transaction_type : str

        inventory_id : typing.Optional[str]

        inventory_external_id : typing.Optional[str]

        amount : typing.Optional[int]

        transaction_amount : typing.Optional[int]

        transaction_date : typing.Optional[str]

        status : typing.Optional[str]

        inventory_type : typing.Optional[str]

        use_unit_value : typing.Optional[bool]

        price : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PublicInventoryTransactionResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/public/inventory-transactions/{jsonable_encoder(transaction_id)}",
            method="PUT",
            json={
                "inventoryId": inventory_id,
                "inventoryExternalId": inventory_external_id,
                "transactionType": transaction_type,
                "amount": amount,
                "transactionAmount": transaction_amount,
                "transactionDate": transaction_date,
                "status": status,
                "inventoryType": inventory_type,
                "useUnitValue": use_unit_value,
                "price": price,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PublicInventoryTransactionResponse,
                    construct_type(
                        type_=PublicInventoryTransactionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def api_routers_v_1_inventory_transactions_public_api_delete_public_inventory_transaction(
        self, transaction_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PublicInventoryTransactionResponse]:
        """
        Parameters
        ----------
        transaction_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PublicInventoryTransactionResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/public/inventory-transactions/{jsonable_encoder(transaction_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PublicInventoryTransactionResponse,
                    construct_type(
                        type_=PublicInventoryTransactionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        construct_type(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
