# This file was auto-generated by Fern from our API Definition.

import contextlib
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.create_public_payment_api_v_2_public_payments_post_200_envelope import (
    CreatePublicPaymentApiV2PublicPaymentsPost200Envelope,
)
from ..types.delete_public_payment_api_v_2_public_payments_payment_id_delete_200_envelope import (
    DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope,
)
from ..types.error_envelope import ErrorEnvelope
from ..types.get_public_payment_api_v_2_public_payments_payment_id_get_200_envelope import (
    GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope,
)
from ..types.list_public_payment_allocations_api_v_2_public_payments_payment_id_allocations_get_200_envelope import (
    ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope,
)
from ..types.list_public_payments_api_v_2_public_payments_get_200_envelope import (
    ListPublicPaymentsApiV2PublicPaymentsGet200Envelope,
)
from ..types.update_public_payment_allocations_api_v_2_public_payments_payment_id_allocations_put_200_envelope import (
    UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope,
)
from ..types.update_public_payment_api_v_2_public_payments_payment_id_put_200_envelope import (
    UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPaymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_public_payments_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListPublicPaymentsApiV2PublicPaymentsGet200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListPublicPaymentsApiV2PublicPaymentsGet200Envelope]
            Object record list response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/public/payments",
            method="GET",
            params={
                "workspace_id": workspace_id,
                "view_id": view_id,
                "search": search,
                "language": language,
                "status": status,
                "usage_status": usage_status,
                "page": page,
                "limit": limit,
                "sort": sort,
            },
            headers={
                "X-Language": str(x_language) if x_language is not None else None,
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPublicPaymentsApiV2PublicPaymentsGet200Envelope,
                    construct_type(
                        type_=ListPublicPaymentsApiV2PublicPaymentsGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_public_payment_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreatePublicPaymentApiV2PublicPaymentsPost200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreatePublicPaymentApiV2PublicPaymentsPost200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/public/payments",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePublicPaymentApiV2PublicPaymentsPost200Envelope,
                    construct_type(
                        type_=CreatePublicPaymentApiV2PublicPaymentsPost200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_public_payment_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope]
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}",
            method="GET",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
                "view_id": view_id,
                "form_view_id": form_view_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope,
                    construct_type(
                        type_=GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_public_payment_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}",
            method="PUT",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope,
                    construct_type(
                        type_=UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_public_payment_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}",
            method="DELETE",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope,
                    construct_type(
                        type_=DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.contextmanager
    def download_public_payment_pdf_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        template_id: typing.Optional[str] = None,
        template_select: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[bytes]]]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        template_id : typing.Optional[str]

        template_select : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[HttpResponse[typing.Iterator[bytes]]]
            PDF document
        """
        with self._client_wrapper.httpx_client.stream(
            f"v2/public/payments/{jsonable_encoder(payment_id)}/pdf",
            method="GET",
            params={
                "external_id": external_id,
                "template_id": template_id,
                "template_select": template_select,
                "language": language,
                "workspace_id": workspace_id,
            },
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return HttpResponse(
                            response=_response, data=(_chunk for _chunk in _response.iter_bytes(chunk_size=_chunk_size))
                        )
                    _response.read()
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorEnvelope,
                                construct_type(
                                    type_=ErrorEnvelope,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorEnvelope,
                                construct_type(
                                    type_=ErrorEnvelope,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()

    def list_public_payment_allocations_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}/allocations",
            method="GET",
            params={
                "external_id": external_id,
                "lang": lang,
                "language": language,
                "workspace_id": workspace_id,
            },
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope,
                    construct_type(
                        type_=ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_public_payment_allocations_api(
        self,
        payment_id: str,
        *,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        external_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        request : typing.Dict[str, typing.Optional[typing.Any]]

        external_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}/allocations",
            method="PUT",
            params={
                "external_id": external_id,
                "lang": lang,
                "language": language,
                "workspace_id": workspace_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope,
                    construct_type(
                        type_=UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPaymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_public_payments_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListPublicPaymentsApiV2PublicPaymentsGet200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListPublicPaymentsApiV2PublicPaymentsGet200Envelope]
            Object record list response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/public/payments",
            method="GET",
            params={
                "workspace_id": workspace_id,
                "view_id": view_id,
                "search": search,
                "language": language,
                "status": status,
                "usage_status": usage_status,
                "page": page,
                "limit": limit,
                "sort": sort,
            },
            headers={
                "X-Language": str(x_language) if x_language is not None else None,
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPublicPaymentsApiV2PublicPaymentsGet200Envelope,
                    construct_type(
                        type_=ListPublicPaymentsApiV2PublicPaymentsGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_public_payment_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreatePublicPaymentApiV2PublicPaymentsPost200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreatePublicPaymentApiV2PublicPaymentsPost200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/public/payments",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePublicPaymentApiV2PublicPaymentsPost200Envelope,
                    construct_type(
                        type_=CreatePublicPaymentApiV2PublicPaymentsPost200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_public_payment_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope]
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}",
            method="GET",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
                "view_id": view_id,
                "form_view_id": form_view_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope,
                    construct_type(
                        type_=GetPublicPaymentApiV2PublicPaymentsPaymentIdGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_public_payment_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}",
            method="PUT",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope,
                    construct_type(
                        type_=UpdatePublicPaymentApiV2PublicPaymentsPaymentIdPut200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_public_payment_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}",
            method="DELETE",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope,
                    construct_type(
                        type_=DeletePublicPaymentApiV2PublicPaymentsPaymentIdDelete200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.asynccontextmanager
    async def download_public_payment_pdf_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        template_id: typing.Optional[str] = None,
        template_select: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        template_id : typing.Optional[str]

        template_select : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[bytes]]]
            PDF document
        """
        async with self._client_wrapper.httpx_client.stream(
            f"v2/public/payments/{jsonable_encoder(payment_id)}/pdf",
            method="GET",
            params={
                "external_id": external_id,
                "template_id": template_id,
                "template_select": template_select,
                "language": language,
                "workspace_id": workspace_id,
            },
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[bytes]]:
                try:
                    if 200 <= _response.status_code < 300:
                        _chunk_size = request_options.get("chunk_size", None) if request_options is not None else None
                        return AsyncHttpResponse(
                            response=_response,
                            data=(_chunk async for _chunk in _response.aiter_bytes(chunk_size=_chunk_size)),
                        )
                    await _response.aread()
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorEnvelope,
                                construct_type(
                                    type_=ErrorEnvelope,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                ErrorEnvelope,
                                construct_type(
                                    type_=ErrorEnvelope,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()

    async def list_public_payment_allocations_api(
        self,
        payment_id: str,
        *,
        external_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        external_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}/allocations",
            method="GET",
            params={
                "external_id": external_id,
                "lang": lang,
                "language": language,
                "workspace_id": workspace_id,
            },
            headers={
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope,
                    construct_type(
                        type_=ListPublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_public_payment_allocations_api(
        self,
        payment_id: str,
        *,
        request: typing.Dict[str, typing.Optional[typing.Any]],
        external_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope]:
        """
        Parameters
        ----------
        payment_id : str

        request : typing.Dict[str, typing.Optional[typing.Any]]

        external_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/payments/{jsonable_encoder(payment_id)}/allocations",
            method="PUT",
            params={
                "external_id": external_id,
                "lang": lang,
                "language": language,
                "workspace_id": workspace_id,
            },
            json=request,
            headers={
                "content-type": "application/json",
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope,
                    construct_type(
                        type_=UpdatePublicPaymentAllocationsApiV2PublicPaymentsPaymentIdAllocationsPut200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
