# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_public_purchase_order_api_v_2_public_purchase_orders_post_200_envelope import (
    CreatePublicPurchaseOrderApiV2PublicPurchaseOrdersPost200Envelope,
)
from ..types.delete_public_purchase_order_api_v_2_public_purchase_orders_purchase_order_id_delete_200_envelope import (
    DeletePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdDelete200Envelope,
)
from ..types.get_public_purchase_order_api_v_2_public_purchase_orders_purchase_order_id_get_200_envelope import (
    GetPublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdGet200Envelope,
)
from ..types.list_public_purchase_orders_api_v_2_public_purchase_orders_get_200_envelope import (
    ListPublicPurchaseOrdersApiV2PublicPurchaseOrdersGet200Envelope,
)
from ..types.update_public_purchase_order_api_v_2_public_purchase_orders_purchase_order_id_put_200_envelope import (
    UpdatePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdPut200Envelope,
)
from ..types.upload_public_purchase_order_file_api_v_2_public_purchase_orders_files_post_200_envelope import (
    UploadPublicPurchaseOrderFileApiV2PublicPurchaseOrdersFilesPost200Envelope,
)
from .raw_client import AsyncRawPurchaseOrdersClient, RawPurchaseOrdersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PurchaseOrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPurchaseOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPurchaseOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPurchaseOrdersClient
        """
        return self._raw_client

    def list_public_purchase_orders_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPublicPurchaseOrdersApiV2PublicPurchaseOrdersGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicPurchaseOrdersApiV2PublicPurchaseOrdersGet200Envelope
            Object record list response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.list_public_purchase_orders_api()
        """
        _response = self._raw_client.list_public_purchase_orders_api(
            workspace_id=workspace_id,
            view_id=view_id,
            search=search,
            language=language,
            status=status,
            usage_status=usage_status,
            page=page,
            limit=limit,
            sort=sort,
            x_language=x_language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def create_public_purchase_order_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePublicPurchaseOrderApiV2PublicPurchaseOrdersPost200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePublicPurchaseOrderApiV2PublicPurchaseOrdersPost200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.create_public_purchase_order_api()
        """
        _response = self._raw_client.create_public_purchase_order_api(
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    def upload_public_purchase_order_file_api(
        self,
        *,
        file: core.File,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadPublicPurchaseOrderFileApiV2PublicPurchaseOrdersFilesPost200Envelope:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadPublicPurchaseOrderFileApiV2PublicPurchaseOrdersFilesPost200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.upload_public_purchase_order_file_api()
        """
        _response = self._raw_client.upload_public_purchase_order_file_api(
            file=file, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def get_public_purchase_order_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdGet200Envelope:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdGet200Envelope
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.get_public_purchase_order_api(
            purchase_order_id="purchase_order_id",
        )
        """
        _response = self._raw_client.get_public_purchase_order_api(
            purchase_order_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            request_options=request_options,
        )
        return _response.data

    def update_public_purchase_order_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdPut200Envelope:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdPut200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.update_public_purchase_order_api(
            purchase_order_id="purchase_order_id",
        )
        """
        _response = self._raw_client.update_public_purchase_order_api(
            purchase_order_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    def delete_public_purchase_order_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdDelete200Envelope:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdDelete200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.delete_public_purchase_order_api(
            purchase_order_id="purchase_order_id",
        )
        """
        _response = self._raw_client.delete_public_purchase_order_api(
            purchase_order_id, external_id=external_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def download_public_purchase_order_pdf_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        template_id: typing.Optional[str] = None,
        template_select: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[bytes]:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        template_id : typing.Optional[str]

        template_select : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            PDF document

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.purchase_orders.download_public_purchase_order_pdf_api(
            purchase_order_id="purchase_order_id",
        )
        """
        with self._raw_client.download_public_purchase_order_pdf_api(
            purchase_order_id,
            external_id=external_id,
            template_id=template_id,
            template_select=template_select,
            language=language,
            workspace_id=workspace_id,
            accept_language=accept_language,
            request_options=request_options,
        ) as r:
            yield from r.data


class AsyncPurchaseOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPurchaseOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPurchaseOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPurchaseOrdersClient
        """
        return self._raw_client

    async def list_public_purchase_orders_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPublicPurchaseOrdersApiV2PublicPurchaseOrdersGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicPurchaseOrdersApiV2PublicPurchaseOrdersGet200Envelope
            Object record list response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.list_public_purchase_orders_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_public_purchase_orders_api(
            workspace_id=workspace_id,
            view_id=view_id,
            search=search,
            language=language,
            status=status,
            usage_status=usage_status,
            page=page,
            limit=limit,
            sort=sort,
            x_language=x_language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def create_public_purchase_order_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePublicPurchaseOrderApiV2PublicPurchaseOrdersPost200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePublicPurchaseOrderApiV2PublicPurchaseOrdersPost200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.create_public_purchase_order_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_public_purchase_order_api(
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    async def upload_public_purchase_order_file_api(
        self,
        *,
        file: core.File,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadPublicPurchaseOrderFileApiV2PublicPurchaseOrdersFilesPost200Envelope:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadPublicPurchaseOrderFileApiV2PublicPurchaseOrdersFilesPost200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.upload_public_purchase_order_file_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_public_purchase_order_file_api(
            file=file, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def get_public_purchase_order_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdGet200Envelope:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdGet200Envelope
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.get_public_purchase_order_api(
                purchase_order_id="purchase_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_public_purchase_order_api(
            purchase_order_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            request_options=request_options,
        )
        return _response.data

    async def update_public_purchase_order_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdPut200Envelope:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdPut200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.update_public_purchase_order_api(
                purchase_order_id="purchase_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_public_purchase_order_api(
            purchase_order_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    async def delete_public_purchase_order_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdDelete200Envelope:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePublicPurchaseOrderApiV2PublicPurchaseOrdersPurchaseOrderIdDelete200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.delete_public_purchase_order_api(
                purchase_order_id="purchase_order_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_public_purchase_order_api(
            purchase_order_id, external_id=external_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def download_public_purchase_order_pdf_api(
        self,
        purchase_order_id: str,
        *,
        external_id: typing.Optional[str] = None,
        template_id: typing.Optional[str] = None,
        template_select: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[bytes]:
        """
        Parameters
        ----------
        purchase_order_id : str

        external_id : typing.Optional[str]

        template_id : typing.Optional[str]

        template_select : typing.Optional[str]

        language : typing.Optional[str]

        workspace_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            PDF document

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchase_orders.download_public_purchase_order_pdf_api(
                purchase_order_id="purchase_order_id",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_public_purchase_order_pdf_api(
            purchase_order_id,
            external_id=external_id,
            template_id=template_id,
            template_select=template_select,
            language=language,
            workspace_id=workspace_id,
            accept_language=accept_language,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk
