# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_public_deal_api_v_2_public_deals_post_200_envelope import (
    CreatePublicDealApiV2PublicDealsPost200Envelope,
)
from ..types.delete_public_deal_api_v_2_public_deals_deal_id_delete_200_envelope import (
    DeletePublicDealApiV2PublicDealsDealIdDelete200Envelope,
)
from ..types.get_public_deal_api_v_2_public_deals_deal_id_get_200_envelope import (
    GetPublicDealApiV2PublicDealsDealIdGet200Envelope,
)
from ..types.list_public_deal_pipelines_api_v_2_public_deals_pipelines_get_200_envelope import (
    ListPublicDealPipelinesApiV2PublicDealsPipelinesGet200Envelope,
)
from ..types.list_public_deals_api_v_2_public_deals_get_200_envelope import (
    ListPublicDealsApiV2PublicDealsGet200Envelope,
)
from ..types.update_public_deal_api_v_2_public_deals_deal_id_put_200_envelope import (
    UpdatePublicDealApiV2PublicDealsDealIdPut200Envelope,
)
from .raw_client import AsyncRawDealsClient, RawDealsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DealsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDealsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDealsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDealsClient
        """
        return self._raw_client

    def list_public_deals_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPublicDealsApiV2PublicDealsGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicDealsApiV2PublicDealsGet200Envelope
            Object record list response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.deals.list_public_deals_api()
        """
        _response = self._raw_client.list_public_deals_api(
            workspace_id=workspace_id,
            view_id=view_id,
            search=search,
            language=language,
            status=status,
            usage_status=usage_status,
            page=page,
            limit=limit,
            sort=sort,
            x_language=x_language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def create_public_deal_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        target: typing.Optional[str] = OMIT,
        provider: typing.Optional[str] = OMIT,
        channel_id: typing.Optional[str] = OMIT,
        external_object_type: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        operation: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        confirm: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePublicDealApiV2PublicDealsPost200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        target : typing.Optional[str]

        provider : typing.Optional[str]

        channel_id : typing.Optional[str]

        external_object_type : typing.Optional[str]

        external_id : typing.Optional[str]

        operation : typing.Optional[str]

        dry_run : typing.Optional[bool]

        confirm : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePublicDealApiV2PublicDealsPost200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.deals.create_public_deal_api()
        """
        _response = self._raw_client.create_public_deal_api(
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            target=target,
            provider=provider,
            channel_id=channel_id,
            external_object_type=external_object_type,
            external_id=external_id,
            operation=operation,
            dry_run=dry_run,
            confirm=confirm,
            request_options=request_options,
        )
        return _response.data

    def list_public_deal_pipelines_api(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ListPublicDealPipelinesApiV2PublicDealsPipelinesGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicDealPipelinesApiV2PublicDealsPipelinesGet200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.deals.list_public_deal_pipelines_api()
        """
        _response = self._raw_client.list_public_deal_pipelines_api(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    def get_public_deal_api(
        self,
        deal_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPublicDealApiV2PublicDealsDealIdGet200Envelope:
        """
        Parameters
        ----------
        deal_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPublicDealApiV2PublicDealsDealIdGet200Envelope
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.deals.get_public_deal_api(
            deal_id="deal_id",
        )
        """
        _response = self._raw_client.get_public_deal_api(
            deal_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            request_options=request_options,
        )
        return _response.data

    def update_public_deal_api(
        self,
        deal_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        target: typing.Optional[str] = OMIT,
        provider: typing.Optional[str] = OMIT,
        channel_id: typing.Optional[str] = OMIT,
        external_object_type: typing.Optional[str] = OMIT,
        public_object_record_mutation_request_external_id: typing.Optional[str] = OMIT,
        operation: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        confirm: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePublicDealApiV2PublicDealsDealIdPut200Envelope:
        """
        Parameters
        ----------
        deal_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        target : typing.Optional[str]

        provider : typing.Optional[str]

        channel_id : typing.Optional[str]

        external_object_type : typing.Optional[str]

        public_object_record_mutation_request_external_id : typing.Optional[str]

        operation : typing.Optional[str]

        dry_run : typing.Optional[bool]

        confirm : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePublicDealApiV2PublicDealsDealIdPut200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.deals.update_public_deal_api(
            deal_id="deal_id",
        )
        """
        _response = self._raw_client.update_public_deal_api(
            deal_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            target=target,
            provider=provider,
            channel_id=channel_id,
            external_object_type=external_object_type,
            public_object_record_mutation_request_external_id=public_object_record_mutation_request_external_id,
            operation=operation,
            dry_run=dry_run,
            confirm=confirm,
            request_options=request_options,
        )
        return _response.data

    def delete_public_deal_api(
        self,
        deal_id: str,
        *,
        external_id: typing.Optional[str] = None,
        target: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        channel_id: typing.Optional[str] = None,
        external_object_type: typing.Optional[str] = None,
        dry_run: typing.Optional[bool] = None,
        confirm: typing.Optional[bool] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePublicDealApiV2PublicDealsDealIdDelete200Envelope:
        """
        Parameters
        ----------
        deal_id : str

        external_id : typing.Optional[str]

        target : typing.Optional[str]

        provider : typing.Optional[str]

        channel_id : typing.Optional[str]

        external_object_type : typing.Optional[str]

        dry_run : typing.Optional[bool]

        confirm : typing.Optional[bool]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePublicDealApiV2PublicDealsDealIdDelete200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.deals.delete_public_deal_api(
            deal_id="deal_id",
        )
        """
        _response = self._raw_client.delete_public_deal_api(
            deal_id,
            external_id=external_id,
            target=target,
            provider=provider,
            channel_id=channel_id,
            external_object_type=external_object_type,
            dry_run=dry_run,
            confirm=confirm,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data


class AsyncDealsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDealsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDealsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDealsClient
        """
        return self._raw_client

    async def list_public_deals_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPublicDealsApiV2PublicDealsGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicDealsApiV2PublicDealsGet200Envelope
            Object record list response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.deals.list_public_deals_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_public_deals_api(
            workspace_id=workspace_id,
            view_id=view_id,
            search=search,
            language=language,
            status=status,
            usage_status=usage_status,
            page=page,
            limit=limit,
            sort=sort,
            x_language=x_language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def create_public_deal_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        target: typing.Optional[str] = OMIT,
        provider: typing.Optional[str] = OMIT,
        channel_id: typing.Optional[str] = OMIT,
        external_object_type: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        operation: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        confirm: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePublicDealApiV2PublicDealsPost200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        target : typing.Optional[str]

        provider : typing.Optional[str]

        channel_id : typing.Optional[str]

        external_object_type : typing.Optional[str]

        external_id : typing.Optional[str]

        operation : typing.Optional[str]

        dry_run : typing.Optional[bool]

        confirm : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePublicDealApiV2PublicDealsPost200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.deals.create_public_deal_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_public_deal_api(
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            target=target,
            provider=provider,
            channel_id=channel_id,
            external_object_type=external_object_type,
            external_id=external_id,
            operation=operation,
            dry_run=dry_run,
            confirm=confirm,
            request_options=request_options,
        )
        return _response.data

    async def list_public_deal_pipelines_api(
        self, *, workspace_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ListPublicDealPipelinesApiV2PublicDealsPipelinesGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicDealPipelinesApiV2PublicDealsPipelinesGet200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.deals.list_public_deal_pipelines_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_public_deal_pipelines_api(
            workspace_id=workspace_id, request_options=request_options
        )
        return _response.data

    async def get_public_deal_api(
        self,
        deal_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPublicDealApiV2PublicDealsDealIdGet200Envelope:
        """
        Parameters
        ----------
        deal_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPublicDealApiV2PublicDealsDealIdGet200Envelope
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.deals.get_public_deal_api(
                deal_id="deal_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_public_deal_api(
            deal_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            request_options=request_options,
        )
        return _response.data

    async def update_public_deal_api(
        self,
        deal_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        target: typing.Optional[str] = OMIT,
        provider: typing.Optional[str] = OMIT,
        channel_id: typing.Optional[str] = OMIT,
        external_object_type: typing.Optional[str] = OMIT,
        public_object_record_mutation_request_external_id: typing.Optional[str] = OMIT,
        operation: typing.Optional[str] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        confirm: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePublicDealApiV2PublicDealsDealIdPut200Envelope:
        """
        Parameters
        ----------
        deal_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        target : typing.Optional[str]

        provider : typing.Optional[str]

        channel_id : typing.Optional[str]

        external_object_type : typing.Optional[str]

        public_object_record_mutation_request_external_id : typing.Optional[str]

        operation : typing.Optional[str]

        dry_run : typing.Optional[bool]

        confirm : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePublicDealApiV2PublicDealsDealIdPut200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.deals.update_public_deal_api(
                deal_id="deal_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_public_deal_api(
            deal_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            target=target,
            provider=provider,
            channel_id=channel_id,
            external_object_type=external_object_type,
            public_object_record_mutation_request_external_id=public_object_record_mutation_request_external_id,
            operation=operation,
            dry_run=dry_run,
            confirm=confirm,
            request_options=request_options,
        )
        return _response.data

    async def delete_public_deal_api(
        self,
        deal_id: str,
        *,
        external_id: typing.Optional[str] = None,
        target: typing.Optional[str] = None,
        provider: typing.Optional[str] = None,
        channel_id: typing.Optional[str] = None,
        external_object_type: typing.Optional[str] = None,
        dry_run: typing.Optional[bool] = None,
        confirm: typing.Optional[bool] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePublicDealApiV2PublicDealsDealIdDelete200Envelope:
        """
        Parameters
        ----------
        deal_id : str

        external_id : typing.Optional[str]

        target : typing.Optional[str]

        provider : typing.Optional[str]

        channel_id : typing.Optional[str]

        external_object_type : typing.Optional[str]

        dry_run : typing.Optional[bool]

        confirm : typing.Optional[bool]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePublicDealApiV2PublicDealsDealIdDelete200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.deals.delete_public_deal_api(
                deal_id="deal_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_public_deal_api(
            deal_id,
            external_id=external_id,
            target=target,
            provider=provider,
            channel_id=channel_id,
            external_object_type=external_object_type,
            dry_run=dry_run,
            confirm=confirm,
            workspace_id=workspace_id,
            request_options=request_options,
        )
        return _response.data
