# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.contact_schema import ContactSchema
from ..types.contacts_list_response import ContactsListResponse
from ..types.public_contact_response import PublicContactResponse
from .raw_client import AsyncRawContactsClient, RawContactsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ContactsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawContactsClient
        """
        return self._raw_client

    def api_routers_v_1_contacts_public_api_public_list_contacts(
        self,
        *,
        view: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        reference_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactsListResponse:
        """
        Parameters
        ----------
        view : typing.Optional[str]

        search : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        reference_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactsListResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.contacts.api_routers_v_1_contacts_public_api_public_list_contacts()
        """
        _response = self._raw_client.api_routers_v_1_contacts_public_api_public_list_contacts(
            view=view,
            search=search,
            page=page,
            limit=limit,
            sort=sort,
            reference_id=reference_id,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_contacts_public_api_create_public_contact(
        self,
        *,
        external_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        company: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        allowed_in_store: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicContactResponse:
        """
        Parameters
        ----------
        external_id : typing.Optional[str]

        name : typing.Optional[str]

        last_name : typing.Optional[str]

        email : typing.Optional[str]

        phone_number : typing.Optional[str]

        company : typing.Optional[str]

        status : typing.Optional[str]

        allowed_in_store : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicContactResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.contacts.api_routers_v_1_contacts_public_api_create_public_contact()
        """
        _response = self._raw_client.api_routers_v_1_contacts_public_api_create_public_contact(
            external_id=external_id,
            name=name,
            last_name=last_name,
            email=email,
            phone_number=phone_number,
            company=company,
            status=status,
            allowed_in_store=allowed_in_store,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_contacts_public_api_get_public_contact(
        self,
        contact_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactSchema:
        """
        Parameters
        ----------
        contact_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactSchema
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.contacts.api_routers_v_1_contacts_public_api_get_public_contact(
            contact_id="contact_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_contacts_public_api_get_public_contact(
            contact_id, external_id=external_id, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_contacts_public_api_update_public_contact(
        self,
        contact_id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        company: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        allowed_in_store: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicContactResponse:
        """
        Parameters
        ----------
        contact_id : str

        external_id : typing.Optional[str]

        name : typing.Optional[str]

        last_name : typing.Optional[str]

        email : typing.Optional[str]

        phone_number : typing.Optional[str]

        company : typing.Optional[str]

        status : typing.Optional[str]

        allowed_in_store : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicContactResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.contacts.api_routers_v_1_contacts_public_api_update_public_contact(
            contact_id="contact_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_contacts_public_api_update_public_contact(
            contact_id,
            external_id=external_id,
            name=name,
            last_name=last_name,
            email=email,
            phone_number=phone_number,
            company=company,
            status=status,
            allowed_in_store=allowed_in_store,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_contacts_public_api_delete_public_contact(
        self,
        contact_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicContactResponse:
        """
        Parameters
        ----------
        contact_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicContactResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.contacts.api_routers_v_1_contacts_public_api_delete_public_contact(
            contact_id="contact_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_contacts_public_api_delete_public_contact(
            contact_id, external_id=external_id, request_options=request_options
        )
        return _response.data


class AsyncContactsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawContactsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawContactsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawContactsClient
        """
        return self._raw_client

    async def api_routers_v_1_contacts_public_api_public_list_contacts(
        self,
        *,
        view: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        reference_id: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactsListResponse:
        """
        Parameters
        ----------
        view : typing.Optional[str]

        search : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        reference_id : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactsListResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.api_routers_v_1_contacts_public_api_public_list_contacts()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_contacts_public_api_public_list_contacts(
            view=view,
            search=search,
            page=page,
            limit=limit,
            sort=sort,
            reference_id=reference_id,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_contacts_public_api_create_public_contact(
        self,
        *,
        external_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        company: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        allowed_in_store: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicContactResponse:
        """
        Parameters
        ----------
        external_id : typing.Optional[str]

        name : typing.Optional[str]

        last_name : typing.Optional[str]

        email : typing.Optional[str]

        phone_number : typing.Optional[str]

        company : typing.Optional[str]

        status : typing.Optional[str]

        allowed_in_store : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicContactResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.api_routers_v_1_contacts_public_api_create_public_contact()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_contacts_public_api_create_public_contact(
            external_id=external_id,
            name=name,
            last_name=last_name,
            email=email,
            phone_number=phone_number,
            company=company,
            status=status,
            allowed_in_store=allowed_in_store,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_contacts_public_api_get_public_contact(
        self,
        contact_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactSchema:
        """
        Parameters
        ----------
        contact_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactSchema
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.api_routers_v_1_contacts_public_api_get_public_contact(
                contact_id="contact_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_contacts_public_api_get_public_contact(
            contact_id, external_id=external_id, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_contacts_public_api_update_public_contact(
        self,
        contact_id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        company: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        allowed_in_store: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicContactResponse:
        """
        Parameters
        ----------
        contact_id : str

        external_id : typing.Optional[str]

        name : typing.Optional[str]

        last_name : typing.Optional[str]

        email : typing.Optional[str]

        phone_number : typing.Optional[str]

        company : typing.Optional[str]

        status : typing.Optional[str]

        allowed_in_store : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicContactResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.api_routers_v_1_contacts_public_api_update_public_contact(
                contact_id="contact_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_contacts_public_api_update_public_contact(
            contact_id,
            external_id=external_id,
            name=name,
            last_name=last_name,
            email=email,
            phone_number=phone_number,
            company=company,
            status=status,
            allowed_in_store=allowed_in_store,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_contacts_public_api_delete_public_contact(
        self,
        contact_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicContactResponse:
        """
        Parameters
        ----------
        contact_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicContactResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.api_routers_v_1_contacts_public_api_delete_public_contact(
                contact_id="contact_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_contacts_public_api_delete_public_contact(
            contact_id, external_id=external_id, request_options=request_options
        )
        return _response.data
