# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.public_property_mutation_response import PublicPropertyMutationResponse
from ..types.public_property_schema import PublicPropertySchema
from ..types.public_property_upsert_request_choice_values import PublicPropertyUpsertRequestChoiceValues
from .raw_client import AsyncRawPropertiesClient, RawPropertiesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PropertiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPropertiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPropertiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPropertiesClient
        """
        return self._raw_client

    def api_routers_v_1_properties_public_api_list_public_properties(
        self,
        object_name: str,
        *,
        workspace_id: typing.Optional[str] = None,
        custom_only: typing.Optional[bool] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[PublicPropertySchema]:
        """
        Parameters
        ----------
        object_name : str

        workspace_id : typing.Optional[str]

        custom_only : typing.Optional[bool]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PublicPropertySchema]
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.properties.api_routers_v_1_properties_public_api_list_public_properties(
            object_name="object_name",
        )
        """
        _response = self._raw_client.api_routers_v_1_properties_public_api_list_public_properties(
            object_name,
            workspace_id=workspace_id,
            custom_only=custom_only,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_properties_public_api_create_public_property(
        self,
        object_name: str,
        *,
        name: typing.Optional[str] = OMIT,
        internal_name: typing.Optional[str] = OMIT,
        type: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        number_format: typing.Optional[str] = OMIT,
        choice_values: typing.Optional[PublicPropertyUpsertRequestChoiceValues] = OMIT,
        conditional_choice_mapping: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        tag_values: typing.Optional[typing.Sequence[str]] = OMIT,
        unique: typing.Optional[bool] = OMIT,
        required_field: typing.Optional[bool] = OMIT,
        multiple_select: typing.Optional[bool] = OMIT,
        show_badge: typing.Optional[bool] = OMIT,
        badge_color: typing.Optional[str] = OMIT,
        order: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicPropertyMutationResponse:
        """
        Parameters
        ----------
        object_name : str

        name : typing.Optional[str]

        internal_name : typing.Optional[str]

        type : typing.Optional[str]

        description : typing.Optional[str]

        number_format : typing.Optional[str]

        choice_values : typing.Optional[PublicPropertyUpsertRequestChoiceValues]

        conditional_choice_mapping : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        tag_values : typing.Optional[typing.Sequence[str]]

        unique : typing.Optional[bool]

        required_field : typing.Optional[bool]

        multiple_select : typing.Optional[bool]

        show_badge : typing.Optional[bool]

        badge_color : typing.Optional[str]

        order : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertyMutationResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.properties.api_routers_v_1_properties_public_api_create_public_property(
            object_name="object_name",
        )
        """
        _response = self._raw_client.api_routers_v_1_properties_public_api_create_public_property(
            object_name,
            name=name,
            internal_name=internal_name,
            type=type,
            description=description,
            number_format=number_format,
            choice_values=choice_values,
            conditional_choice_mapping=conditional_choice_mapping,
            tag_values=tag_values,
            unique=unique,
            required_field=required_field,
            multiple_select=multiple_select,
            show_badge=show_badge,
            badge_color=badge_color,
            order=order,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_properties_public_api_retrieve_public_property(
        self,
        object_name: str,
        property_ref: str,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicPropertySchema:
        """
        Parameters
        ----------
        object_name : str

        property_ref : str

        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertySchema
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.properties.api_routers_v_1_properties_public_api_retrieve_public_property(
            object_name="object_name",
            property_ref="property_ref",
        )
        """
        _response = self._raw_client.api_routers_v_1_properties_public_api_retrieve_public_property(
            object_name,
            property_ref,
            workspace_id=workspace_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_properties_public_api_update_public_property(
        self,
        object_name: str,
        property_ref: str,
        *,
        name: typing.Optional[str] = OMIT,
        internal_name: typing.Optional[str] = OMIT,
        type: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        number_format: typing.Optional[str] = OMIT,
        choice_values: typing.Optional[PublicPropertyUpsertRequestChoiceValues] = OMIT,
        conditional_choice_mapping: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        tag_values: typing.Optional[typing.Sequence[str]] = OMIT,
        unique: typing.Optional[bool] = OMIT,
        required_field: typing.Optional[bool] = OMIT,
        multiple_select: typing.Optional[bool] = OMIT,
        show_badge: typing.Optional[bool] = OMIT,
        badge_color: typing.Optional[str] = OMIT,
        order: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicPropertyMutationResponse:
        """
        Parameters
        ----------
        object_name : str

        property_ref : str

        name : typing.Optional[str]

        internal_name : typing.Optional[str]

        type : typing.Optional[str]

        description : typing.Optional[str]

        number_format : typing.Optional[str]

        choice_values : typing.Optional[PublicPropertyUpsertRequestChoiceValues]

        conditional_choice_mapping : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        tag_values : typing.Optional[typing.Sequence[str]]

        unique : typing.Optional[bool]

        required_field : typing.Optional[bool]

        multiple_select : typing.Optional[bool]

        show_badge : typing.Optional[bool]

        badge_color : typing.Optional[str]

        order : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertyMutationResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.properties.api_routers_v_1_properties_public_api_update_public_property(
            object_name="object_name",
            property_ref="property_ref",
        )
        """
        _response = self._raw_client.api_routers_v_1_properties_public_api_update_public_property(
            object_name,
            property_ref,
            name=name,
            internal_name=internal_name,
            type=type,
            description=description,
            number_format=number_format,
            choice_values=choice_values,
            conditional_choice_mapping=conditional_choice_mapping,
            tag_values=tag_values,
            unique=unique,
            required_field=required_field,
            multiple_select=multiple_select,
            show_badge=show_badge,
            badge_color=badge_color,
            order=order,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_properties_public_api_delete_public_property(
        self, object_name: str, property_ref: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PublicPropertyMutationResponse:
        """
        Parameters
        ----------
        object_name : str

        property_ref : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertyMutationResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.properties.api_routers_v_1_properties_public_api_delete_public_property(
            object_name="object_name",
            property_ref="property_ref",
        )
        """
        _response = self._raw_client.api_routers_v_1_properties_public_api_delete_public_property(
            object_name, property_ref, request_options=request_options
        )
        return _response.data


class AsyncPropertiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPropertiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPropertiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPropertiesClient
        """
        return self._raw_client

    async def api_routers_v_1_properties_public_api_list_public_properties(
        self,
        object_name: str,
        *,
        workspace_id: typing.Optional[str] = None,
        custom_only: typing.Optional[bool] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[PublicPropertySchema]:
        """
        Parameters
        ----------
        object_name : str

        workspace_id : typing.Optional[str]

        custom_only : typing.Optional[bool]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PublicPropertySchema]
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.properties.api_routers_v_1_properties_public_api_list_public_properties(
                object_name="object_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_properties_public_api_list_public_properties(
            object_name,
            workspace_id=workspace_id,
            custom_only=custom_only,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_properties_public_api_create_public_property(
        self,
        object_name: str,
        *,
        name: typing.Optional[str] = OMIT,
        internal_name: typing.Optional[str] = OMIT,
        type: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        number_format: typing.Optional[str] = OMIT,
        choice_values: typing.Optional[PublicPropertyUpsertRequestChoiceValues] = OMIT,
        conditional_choice_mapping: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        tag_values: typing.Optional[typing.Sequence[str]] = OMIT,
        unique: typing.Optional[bool] = OMIT,
        required_field: typing.Optional[bool] = OMIT,
        multiple_select: typing.Optional[bool] = OMIT,
        show_badge: typing.Optional[bool] = OMIT,
        badge_color: typing.Optional[str] = OMIT,
        order: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicPropertyMutationResponse:
        """
        Parameters
        ----------
        object_name : str

        name : typing.Optional[str]

        internal_name : typing.Optional[str]

        type : typing.Optional[str]

        description : typing.Optional[str]

        number_format : typing.Optional[str]

        choice_values : typing.Optional[PublicPropertyUpsertRequestChoiceValues]

        conditional_choice_mapping : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        tag_values : typing.Optional[typing.Sequence[str]]

        unique : typing.Optional[bool]

        required_field : typing.Optional[bool]

        multiple_select : typing.Optional[bool]

        show_badge : typing.Optional[bool]

        badge_color : typing.Optional[str]

        order : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertyMutationResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.properties.api_routers_v_1_properties_public_api_create_public_property(
                object_name="object_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_properties_public_api_create_public_property(
            object_name,
            name=name,
            internal_name=internal_name,
            type=type,
            description=description,
            number_format=number_format,
            choice_values=choice_values,
            conditional_choice_mapping=conditional_choice_mapping,
            tag_values=tag_values,
            unique=unique,
            required_field=required_field,
            multiple_select=multiple_select,
            show_badge=show_badge,
            badge_color=badge_color,
            order=order,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_properties_public_api_retrieve_public_property(
        self,
        object_name: str,
        property_ref: str,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicPropertySchema:
        """
        Parameters
        ----------
        object_name : str

        property_ref : str

        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertySchema
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.properties.api_routers_v_1_properties_public_api_retrieve_public_property(
                object_name="object_name",
                property_ref="property_ref",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_properties_public_api_retrieve_public_property(
            object_name,
            property_ref,
            workspace_id=workspace_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_properties_public_api_update_public_property(
        self,
        object_name: str,
        property_ref: str,
        *,
        name: typing.Optional[str] = OMIT,
        internal_name: typing.Optional[str] = OMIT,
        type: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        number_format: typing.Optional[str] = OMIT,
        choice_values: typing.Optional[PublicPropertyUpsertRequestChoiceValues] = OMIT,
        conditional_choice_mapping: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        tag_values: typing.Optional[typing.Sequence[str]] = OMIT,
        unique: typing.Optional[bool] = OMIT,
        required_field: typing.Optional[bool] = OMIT,
        multiple_select: typing.Optional[bool] = OMIT,
        show_badge: typing.Optional[bool] = OMIT,
        badge_color: typing.Optional[str] = OMIT,
        order: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicPropertyMutationResponse:
        """
        Parameters
        ----------
        object_name : str

        property_ref : str

        name : typing.Optional[str]

        internal_name : typing.Optional[str]

        type : typing.Optional[str]

        description : typing.Optional[str]

        number_format : typing.Optional[str]

        choice_values : typing.Optional[PublicPropertyUpsertRequestChoiceValues]

        conditional_choice_mapping : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        tag_values : typing.Optional[typing.Sequence[str]]

        unique : typing.Optional[bool]

        required_field : typing.Optional[bool]

        multiple_select : typing.Optional[bool]

        show_badge : typing.Optional[bool]

        badge_color : typing.Optional[str]

        order : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertyMutationResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.properties.api_routers_v_1_properties_public_api_update_public_property(
                object_name="object_name",
                property_ref="property_ref",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_properties_public_api_update_public_property(
            object_name,
            property_ref,
            name=name,
            internal_name=internal_name,
            type=type,
            description=description,
            number_format=number_format,
            choice_values=choice_values,
            conditional_choice_mapping=conditional_choice_mapping,
            tag_values=tag_values,
            unique=unique,
            required_field=required_field,
            multiple_select=multiple_select,
            show_badge=show_badge,
            badge_color=badge_color,
            order=order,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_properties_public_api_delete_public_property(
        self, object_name: str, property_ref: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PublicPropertyMutationResponse:
        """
        Parameters
        ----------
        object_name : str

        property_ref : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicPropertyMutationResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.properties.api_routers_v_1_properties_public_api_delete_public_property(
                object_name="object_name",
                property_ref="property_ref",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_properties_public_api_delete_public_property(
            object_name, property_ref, request_options=request_options
        )
        return _response.data
