# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.expense_schema import ExpenseSchema
from ..types.public_expense_attachment_payload import PublicExpenseAttachmentPayload
from ..types.public_expense_file_upload_response import PublicExpenseFileUploadResponse
from ..types.public_expense_response import PublicExpenseResponse
from .raw_client import AsyncRawExpensesClient, RawExpensesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ExpensesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawExpensesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawExpensesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawExpensesClient
        """
        return self._raw_client

    def api_routers_v_1_expenses_public_api_list_workspace_expenses(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ExpenseSchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ExpenseSchema]
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.expenses.api_routers_v_1_expenses_public_api_list_workspace_expenses()
        """
        _response = self._raw_client.api_routers_v_1_expenses_public_api_list_workspace_expenses(
            workspace_id=workspace_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_expenses_public_api_create_public_expense(
        self,
        *,
        external_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[str] = OMIT,
        contact_external_id: typing.Optional[str] = OMIT,
        company_id: typing.Optional[str] = OMIT,
        company_external_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        reimburse_date: typing.Optional[str] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        amount: typing.Optional[float] = OMIT,
        attachment_file: typing.Optional[PublicExpenseAttachmentPayload] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicExpenseResponse:
        """
        Parameters
        ----------
        external_id : typing.Optional[str]

        contact_id : typing.Optional[str]

        contact_external_id : typing.Optional[str]

        company_id : typing.Optional[str]

        company_external_id : typing.Optional[str]

        description : typing.Optional[str]

        reimburse_date : typing.Optional[str]

        due_date : typing.Optional[str]

        status : typing.Optional[str]

        currency : typing.Optional[str]

        amount : typing.Optional[float]

        attachment_file : typing.Optional[PublicExpenseAttachmentPayload]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.expenses.api_routers_v_1_expenses_public_api_create_public_expense()
        """
        _response = self._raw_client.api_routers_v_1_expenses_public_api_create_public_expense(
            external_id=external_id,
            contact_id=contact_id,
            contact_external_id=contact_external_id,
            company_id=company_id,
            company_external_id=company_external_id,
            description=description,
            reimburse_date=reimburse_date,
            due_date=due_date,
            status=status,
            currency=currency,
            amount=amount,
            attachment_file=attachment_file,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_expenses_public_api_upload_public_expense_file(
        self, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> PublicExpenseFileUploadResponse:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseFileUploadResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.expenses.api_routers_v_1_expenses_public_api_upload_public_expense_file()
        """
        _response = self._raw_client.api_routers_v_1_expenses_public_api_upload_public_expense_file(
            file=file, request_options=request_options
        )
        return _response.data

    def api_routers_v_1_expenses_public_api_get_public_expense(
        self,
        expense_id: str,
        *,
        external_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExpenseSchema:
        """
        Parameters
        ----------
        expense_id : str

        external_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExpenseSchema
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.expenses.api_routers_v_1_expenses_public_api_get_public_expense(
            expense_id="expense_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_expenses_public_api_get_public_expense(
            expense_id,
            external_id=external_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_expenses_public_api_update_public_expense(
        self,
        expense_id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[str] = OMIT,
        contact_external_id: typing.Optional[str] = OMIT,
        company_id: typing.Optional[str] = OMIT,
        company_external_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        reimburse_date: typing.Optional[str] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        amount: typing.Optional[float] = OMIT,
        attachment_file: typing.Optional[PublicExpenseAttachmentPayload] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicExpenseResponse:
        """
        Parameters
        ----------
        expense_id : str

        external_id : typing.Optional[str]

        contact_id : typing.Optional[str]

        contact_external_id : typing.Optional[str]

        company_id : typing.Optional[str]

        company_external_id : typing.Optional[str]

        description : typing.Optional[str]

        reimburse_date : typing.Optional[str]

        due_date : typing.Optional[str]

        status : typing.Optional[str]

        currency : typing.Optional[str]

        amount : typing.Optional[float]

        attachment_file : typing.Optional[PublicExpenseAttachmentPayload]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.expenses.api_routers_v_1_expenses_public_api_update_public_expense(
            expense_id="expense_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_expenses_public_api_update_public_expense(
            expense_id,
            external_id=external_id,
            contact_id=contact_id,
            contact_external_id=contact_external_id,
            company_id=company_id,
            company_external_id=company_external_id,
            description=description,
            reimburse_date=reimburse_date,
            due_date=due_date,
            status=status,
            currency=currency,
            amount=amount,
            attachment_file=attachment_file,
            request_options=request_options,
        )
        return _response.data

    def api_routers_v_1_expenses_public_api_delete_public_expense(
        self,
        expense_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicExpenseResponse:
        """
        Parameters
        ----------
        expense_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseResponse
            OK

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            token="YOUR_TOKEN",
        )
        client.expenses.api_routers_v_1_expenses_public_api_delete_public_expense(
            expense_id="expense_id",
        )
        """
        _response = self._raw_client.api_routers_v_1_expenses_public_api_delete_public_expense(
            expense_id, external_id=external_id, request_options=request_options
        )
        return _response.data


class AsyncExpensesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawExpensesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawExpensesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawExpensesClient
        """
        return self._raw_client

    async def api_routers_v_1_expenses_public_api_list_workspace_expenses(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ExpenseSchema]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ExpenseSchema]
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.expenses.api_routers_v_1_expenses_public_api_list_workspace_expenses()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_expenses_public_api_list_workspace_expenses(
            workspace_id=workspace_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_expenses_public_api_create_public_expense(
        self,
        *,
        external_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[str] = OMIT,
        contact_external_id: typing.Optional[str] = OMIT,
        company_id: typing.Optional[str] = OMIT,
        company_external_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        reimburse_date: typing.Optional[str] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        amount: typing.Optional[float] = OMIT,
        attachment_file: typing.Optional[PublicExpenseAttachmentPayload] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicExpenseResponse:
        """
        Parameters
        ----------
        external_id : typing.Optional[str]

        contact_id : typing.Optional[str]

        contact_external_id : typing.Optional[str]

        company_id : typing.Optional[str]

        company_external_id : typing.Optional[str]

        description : typing.Optional[str]

        reimburse_date : typing.Optional[str]

        due_date : typing.Optional[str]

        status : typing.Optional[str]

        currency : typing.Optional[str]

        amount : typing.Optional[float]

        attachment_file : typing.Optional[PublicExpenseAttachmentPayload]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.expenses.api_routers_v_1_expenses_public_api_create_public_expense()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_expenses_public_api_create_public_expense(
            external_id=external_id,
            contact_id=contact_id,
            contact_external_id=contact_external_id,
            company_id=company_id,
            company_external_id=company_external_id,
            description=description,
            reimburse_date=reimburse_date,
            due_date=due_date,
            status=status,
            currency=currency,
            amount=amount,
            attachment_file=attachment_file,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_expenses_public_api_upload_public_expense_file(
        self, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> PublicExpenseFileUploadResponse:
        """
        Parameters
        ----------
        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseFileUploadResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.expenses.api_routers_v_1_expenses_public_api_upload_public_expense_file()


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_expenses_public_api_upload_public_expense_file(
            file=file, request_options=request_options
        )
        return _response.data

    async def api_routers_v_1_expenses_public_api_get_public_expense(
        self,
        expense_id: str,
        *,
        external_id: typing.Optional[str] = None,
        lang: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExpenseSchema:
        """
        Parameters
        ----------
        expense_id : str

        external_id : typing.Optional[str]

        lang : typing.Optional[str]

        language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExpenseSchema
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.expenses.api_routers_v_1_expenses_public_api_get_public_expense(
                expense_id="expense_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_expenses_public_api_get_public_expense(
            expense_id,
            external_id=external_id,
            lang=lang,
            language=language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_expenses_public_api_update_public_expense(
        self,
        expense_id: str,
        *,
        external_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[str] = OMIT,
        contact_external_id: typing.Optional[str] = OMIT,
        company_id: typing.Optional[str] = OMIT,
        company_external_id: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        reimburse_date: typing.Optional[str] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        status: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        amount: typing.Optional[float] = OMIT,
        attachment_file: typing.Optional[PublicExpenseAttachmentPayload] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicExpenseResponse:
        """
        Parameters
        ----------
        expense_id : str

        external_id : typing.Optional[str]

        contact_id : typing.Optional[str]

        contact_external_id : typing.Optional[str]

        company_id : typing.Optional[str]

        company_external_id : typing.Optional[str]

        description : typing.Optional[str]

        reimburse_date : typing.Optional[str]

        due_date : typing.Optional[str]

        status : typing.Optional[str]

        currency : typing.Optional[str]

        amount : typing.Optional[float]

        attachment_file : typing.Optional[PublicExpenseAttachmentPayload]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.expenses.api_routers_v_1_expenses_public_api_update_public_expense(
                expense_id="expense_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_expenses_public_api_update_public_expense(
            expense_id,
            external_id=external_id,
            contact_id=contact_id,
            contact_external_id=contact_external_id,
            company_id=company_id,
            company_external_id=company_external_id,
            description=description,
            reimburse_date=reimburse_date,
            due_date=due_date,
            status=status,
            currency=currency,
            amount=amount,
            attachment_file=attachment_file,
            request_options=request_options,
        )
        return _response.data

    async def api_routers_v_1_expenses_public_api_delete_public_expense(
        self,
        expense_id: str,
        *,
        external_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicExpenseResponse:
        """
        Parameters
        ----------
        expense_id : str

        external_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicExpenseResponse
            OK

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.expenses.api_routers_v_1_expenses_public_api_delete_public_expense(
                expense_id="expense_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.api_routers_v_1_expenses_public_api_delete_public_expense(
            expense_id, external_id=external_id, request_options=request_options
        )
        return _response.data
