# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_public_location_api_v_2_public_locations_post_200_envelope import (
    CreatePublicLocationApiV2PublicLocationsPost200Envelope,
)
from ..types.delete_public_location_api_v_2_public_locations_location_id_delete_200_envelope import (
    DeletePublicLocationApiV2PublicLocationsLocationIdDelete200Envelope,
)
from ..types.get_public_location_api_v_2_public_locations_location_id_get_200_envelope import (
    GetPublicLocationApiV2PublicLocationsLocationIdGet200Envelope,
)
from ..types.list_public_locations_api_v_2_public_locations_get_200_envelope import (
    ListPublicLocationsApiV2PublicLocationsGet200Envelope,
)
from ..types.update_public_location_api_v_2_public_locations_location_id_put_200_envelope import (
    UpdatePublicLocationApiV2PublicLocationsLocationIdPut200Envelope,
)
from .raw_client import AsyncRawLocationsClient, RawLocationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class LocationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLocationsClient
        """
        return self._raw_client

    def list_public_locations_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPublicLocationsApiV2PublicLocationsGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicLocationsApiV2PublicLocationsGet200Envelope
            Object record list response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.locations.list_public_locations_api()
        """
        _response = self._raw_client.list_public_locations_api(
            workspace_id=workspace_id,
            view_id=view_id,
            search=search,
            language=language,
            status=status,
            usage_status=usage_status,
            page=page,
            limit=limit,
            sort=sort,
            x_language=x_language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    def create_public_location_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePublicLocationApiV2PublicLocationsPost200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePublicLocationApiV2PublicLocationsPost200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.locations.create_public_location_api()
        """
        _response = self._raw_client.create_public_location_api(
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    def get_public_location_api(
        self,
        location_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPublicLocationApiV2PublicLocationsLocationIdGet200Envelope:
        """
        Parameters
        ----------
        location_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPublicLocationApiV2PublicLocationsLocationIdGet200Envelope
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.locations.get_public_location_api(
            location_id="location_id",
        )
        """
        _response = self._raw_client.get_public_location_api(
            location_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            request_options=request_options,
        )
        return _response.data

    def update_public_location_api(
        self,
        location_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePublicLocationApiV2PublicLocationsLocationIdPut200Envelope:
        """
        Parameters
        ----------
        location_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePublicLocationApiV2PublicLocationsLocationIdPut200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.locations.update_public_location_api(
            location_id="location_id",
        )
        """
        _response = self._raw_client.update_public_location_api(
            location_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    def delete_public_location_api(
        self,
        location_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePublicLocationApiV2PublicLocationsLocationIdDelete200Envelope:
        """
        Parameters
        ----------
        location_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePublicLocationApiV2PublicLocationsLocationIdDelete200Envelope
            Successful Response

        Examples
        --------
        from sanka_sdk import SankaClient

        client = SankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )
        client.locations.delete_public_location_api(
            location_id="location_id",
        )
        """
        _response = self._raw_client.delete_public_location_api(
            location_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data


class AsyncLocationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLocationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLocationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLocationsClient
        """
        return self._raw_client

    async def list_public_locations_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPublicLocationsApiV2PublicLocationsGet200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPublicLocationsApiV2PublicLocationsGet200Envelope
            Object record list response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.locations.list_public_locations_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_public_locations_api(
            workspace_id=workspace_id,
            view_id=view_id,
            search=search,
            language=language,
            status=status,
            usage_status=usage_status,
            page=page,
            limit=limit,
            sort=sort,
            x_language=x_language,
            accept_language=accept_language,
            request_options=request_options,
        )
        return _response.data

    async def create_public_location_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePublicLocationApiV2PublicLocationsPost200Envelope:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePublicLocationApiV2PublicLocationsPost200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.locations.create_public_location_api()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_public_location_api(
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    async def get_public_location_api(
        self,
        location_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetPublicLocationApiV2PublicLocationsLocationIdGet200Envelope:
        """
        Parameters
        ----------
        location_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPublicLocationApiV2PublicLocationsLocationIdGet200Envelope
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.locations.get_public_location_api(
                location_id="location_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_public_location_api(
            location_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            request_options=request_options,
        )
        return _response.data

    async def update_public_location_api(
        self,
        location_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePublicLocationApiV2PublicLocationsLocationIdPut200Envelope:
        """
        Parameters
        ----------
        location_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePublicLocationApiV2PublicLocationsLocationIdPut200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.locations.update_public_location_api(
                location_id="location_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_public_location_api(
            location_id,
            external_id=external_id,
            workspace_id=workspace_id,
            view_id=view_id,
            form_view_id=form_view_id,
            properties=properties,
            request_options=request_options,
        )
        return _response.data

    async def delete_public_location_api(
        self,
        location_id: str,
        *,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePublicLocationApiV2PublicLocationsLocationIdDelete200Envelope:
        """
        Parameters
        ----------
        location_id : str

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePublicLocationApiV2PublicLocationsLocationIdDelete200Envelope
            Successful Response

        Examples
        --------
        import asyncio

        from sanka_sdk import AsyncSankaClient

        client = AsyncSankaClient(
            workspace_code="YOUR_WORKSPACE_CODE",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.locations.delete_public_location_api(
                location_id="location_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_public_location_api(
            location_id, workspace_id=workspace_id, request_options=request_options
        )
        return _response.data
