# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .bulk_order_item_in import BulkOrderItemIn


class BulkOrderIn(UncheckedBaseModel):
    external_id: typing_extensions.Annotated[str, FieldMetadata(alias="externalId")]
    company_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="companyId")] = None
    company_external_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="companyExternalId")] = (
        None
    )
    order_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="orderAt")] = None
    delivery_status: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="deliveryStatus")] = None
    items: typing.List[BulkOrderItemIn]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
