# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .developer_cloud_certificate_evidence_profile import DeveloperCloudCertificateEvidenceProfile
from .developer_cloud_scenario_evidence import DeveloperCloudScenarioEvidence


class DeveloperCloudCertificateEvidence(UncheckedBaseModel):
    profile: typing.Optional[DeveloperCloudCertificateEvidenceProfile] = None
    candidate_sha_256: typing_extensions.Annotated[str, FieldMetadata(alias="candidate_sha256")]
    plan_sha_256: typing_extensions.Annotated[str, FieldMetadata(alias="plan_sha256")]
    dependency_lock_sha_256: typing_extensions.Annotated[str, FieldMetadata(alias="dependency_lock_sha256")]
    generated_tests: int
    generated_checks_passed: bool
    scenarios: typing.List[DeveloperCloudScenarioEvidence]
    declared_routes: typing.List[str]
    tested_routes: typing.List[str]
    untested_routes: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
