# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .ferry_diagram_node_data import FerryDiagramNodeData
from .ferry_diagram_node_type import FerryDiagramNodeType
from .ferry_diagram_position import FerryDiagramPosition


class FerryDiagramNode(UncheckedBaseModel):
    id: str
    type: FerryDiagramNodeType
    position: FerryDiagramPosition
    data: FerryDiagramNodeData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
