# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .search_filter_expression import SearchFilterExpression


class GoalMetricDefinition(UncheckedBaseModel):
    """
    What a goal counts or sums: one object's active records, by the month of one of their
    dates, narrowed by filters (the same expressions as saved views).
    """

    source: str
    measure: typing.Optional[str] = None
    date_field: typing.Optional[str] = None
    filters: typing.Optional[typing.List[SearchFilterExpression]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
