# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .envelope_meta import EnvelopeMeta
from .object_record_list_data import ObjectRecordListData


class ListPublicDealsApiV2PublicDealsGet200Envelope(UncheckedBaseModel):
    success: typing.Literal[True] = True
    data: ObjectRecordListData
    meta: EnvelopeMeta

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
