# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class MoveSlidesOp(UncheckedBaseModel):
    slide_ids: typing_extensions.Annotated[typing.List[str], FieldMetadata(alias="slideIds")]
    after: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slide to move after; null moves first; omit to move last.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
