# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class OfferSnapshotData(UncheckedBaseModel):
    id: str
    buy_request_id: str
    buy_request_line_id: str
    sourcing_run_id: typing.Optional[str] = None
    provider: str
    merchant_key: str
    merchant_name: str
    merchant_domain: typing.Optional[str] = None
    provider_product_id: typing.Optional[str] = None
    upid: typing.Optional[str] = None
    title: str
    variant_title: typing.Optional[str] = None
    product_url: typing.Optional[str] = None
    image_url: typing.Optional[str] = None
    quantity: float
    unit_price: typing.Optional[float] = None
    shipping_amount: typing.Optional[float] = None
    tax_amount: typing.Optional[float] = None
    total_amount: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    availability: typing.Optional[str] = None
    delivery_estimate: typing.Optional[str] = None
    raw_snapshot: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    snapshot_hash: str
    snapshot_version: int
    captured_at: dt.datetime
    expires_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
