# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .presentation_export_request_format import PresentationExportRequestFormat


class PresentationExportRequest(UncheckedBaseModel):
    format: PresentationExportRequestFormat
    slide_ids: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="slideIds")] = None
    include_hidden: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="includeHidden")] = None
    include_notes: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="includeNotes")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
