# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .public_report_panel_detail_schema import PublicReportPanelDetailSchema


class PublicReportDetailSchema(UncheckedBaseModel):
    id: str
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    report_type: typing.Optional[str] = None
    panel_count: typing.Optional[int] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    panels: typing.Optional[typing.List[PublicReportPanelDetailSchema]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
