# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .public_property_mutation_request_choice_values import PublicPropertyMutationRequestChoiceValues


class PublicPropertyMutationRequest(UncheckedBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    internal_name: typing.Optional[str] = None
    choice_values: typing.Optional[PublicPropertyMutationRequestChoiceValues] = None
    choice_labels: typing.Optional[typing.List[str]] = None
    choice_colors: typing.Optional[typing.List[str]] = None
    target: typing.Optional[str] = None
    language: typing.Optional[str] = None
    custom_object_id: typing.Optional[str] = None
    editor_variant: typing.Optional[str] = None
    source: typing.Optional[str] = None
    scope: typing.Optional[str] = None
    provider: typing.Optional[str] = None
    channel_id: typing.Optional[str] = None
    external_object_type: typing.Optional[str] = None
    external_id: typing.Optional[str] = None
    field_type: typing.Optional[str] = None
    group_name: typing.Optional[str] = None
    options: typing.Optional[typing.List[typing.Dict[str, typing.Optional[typing.Any]]]] = None
    dry_run: typing.Optional[bool] = None
    confirm: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
