# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .public_report_metric_schema import PublicReportMetricSchema


class PublicReportPanelDetailSchema(UncheckedBaseModel):
    id: str
    order: int
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    panel_type: typing.Optional[str] = None
    data_source_type: typing.Optional[str] = None
    data_source: typing.Optional[str] = None
    width_units: typing.Optional[int] = None
    height_px: typing.Optional[int] = None
    breakdown: typing.Optional[str] = None
    ratio: typing.Optional[int] = None
    filter: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    meta_data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    type_objects: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    metrics: typing.Optional[typing.List[PublicReportMetricSchema]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
