# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .public_report_metric_request import PublicReportMetricRequest


class PublicReportPanelRequest(UncheckedBaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    panel_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="panelType")] = None
    data_source_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="dataSourceType")] = None
    data_source: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="dataSource")] = None
    data_sources: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="dataSources")] = (
        None
    )
    width_units: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="widthUnits")] = None
    height_px: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="heightPx")] = None
    ratio: typing.Optional[int] = None
    breakdown: typing.Optional[str] = None
    filter: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    meta_data: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]], FieldMetadata(alias="metaData")
    ] = None
    type_objects: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="typeObjects")] = (
        None
    )
    metrics: typing.Optional[typing.List[PublicReportMetricRequest]] = None
    order: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
