# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .subscription_contact_schema import SubscriptionContactSchema
from .subscription_item_schema import SubscriptionItemSchema


class SubscriptionDetailSchema(UncheckedBaseModel):
    id: str
    status: typing.Optional[str] = None
    subscription_status: typing.Optional[str] = None
    created_at: dt.datetime
    contact_info: typing.List[SubscriptionContactSchema]
    items: typing.List[SubscriptionItemSchema]
    number_item: int
    start_date: typing.Optional[dt.date] = None
    currency: typing.Optional[str] = None
    total_price: typing.Optional[float] = None
    prior_to_time: typing.Optional[str] = None
    frequency: typing.Optional[int] = None
    frequency_time: typing.Optional[str] = None
    tax: typing.Optional[float] = None
    shipping_cost_tax_status: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
