# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.create_public_subscription_api_v_2_public_subscriptions_post_200_envelope import (
    CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope,
)
from ..types.delete_public_subscription_api_v_2_public_subscriptions_subscription_id_delete_200_envelope import (
    DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope,
)
from ..types.error_envelope import ErrorEnvelope
from ..types.get_public_subscription_api_v_2_public_subscriptions_subscription_id_get_200_envelope import (
    GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope,
)
from ..types.list_public_subscriptions_api_v_2_public_subscriptions_get_200_envelope import (
    ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope,
)
from ..types.update_public_subscription_api_v_2_public_subscriptions_subscription_id_put_200_envelope import (
    UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSubscriptionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_public_subscriptions_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope]
            Object record list response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/public/subscriptions",
            method="GET",
            params={
                "workspace_id": workspace_id,
                "view_id": view_id,
                "search": search,
                "language": language,
                "status": status,
                "usage_status": usage_status,
                "page": page,
                "limit": limit,
                "sort": sort,
            },
            headers={
                "X-Language": str(x_language) if x_language is not None else None,
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope,
                    construct_type(
                        type_=ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_public_subscription_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/public/subscriptions",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope,
                    construct_type(
                        type_=CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_public_subscription_api(
        self,
        subscription_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope]:
        """
        Parameters
        ----------
        subscription_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope]
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/subscriptions/{jsonable_encoder(subscription_id)}",
            method="GET",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
                "view_id": view_id,
                "form_view_id": form_view_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope,
                    construct_type(
                        type_=GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_public_subscription_api(
        self,
        subscription_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope]:
        """
        Parameters
        ----------
        subscription_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/subscriptions/{jsonable_encoder(subscription_id)}",
            method="PUT",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope,
                    construct_type(
                        type_=UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_public_subscription_api(
        self,
        subscription_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope]:
        """
        Parameters
        ----------
        subscription_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/public/subscriptions/{jsonable_encoder(subscription_id)}",
            method="DELETE",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope,
                    construct_type(
                        type_=DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSubscriptionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_public_subscriptions_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        language: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        usage_status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        x_language: typing.Optional[str] = None,
        accept_language: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        search : typing.Optional[str]

        language : typing.Optional[str]

        status : typing.Optional[str]

        usage_status : typing.Optional[str]

        page : typing.Optional[int]

        limit : typing.Optional[int]

        sort : typing.Optional[str]

        x_language : typing.Optional[str]

        accept_language : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope]
            Object record list response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/public/subscriptions",
            method="GET",
            params={
                "workspace_id": workspace_id,
                "view_id": view_id,
                "search": search,
                "language": language,
                "status": status,
                "usage_status": usage_status,
                "page": page,
                "limit": limit,
                "sort": sort,
            },
            headers={
                "X-Language": str(x_language) if x_language is not None else None,
                "Accept-Language": str(accept_language) if accept_language is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope,
                    construct_type(
                        type_=ListPublicSubscriptionsApiV2PublicSubscriptionsGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_public_subscription_api(
        self,
        *,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope]:
        """
        Parameters
        ----------
        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/public/subscriptions",
            method="POST",
            params={
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope,
                    construct_type(
                        type_=CreatePublicSubscriptionApiV2PublicSubscriptionsPost200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_public_subscription_api(
        self,
        subscription_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = None,
        form_view_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope]:
        """
        Parameters
        ----------
        subscription_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope]
            Object record detail response. The base detail payload is intentionally thin; drawer sections load through scoped endpoints.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/subscriptions/{jsonable_encoder(subscription_id)}",
            method="GET",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
                "view_id": view_id,
                "form_view_id": form_view_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope,
                    construct_type(
                        type_=GetPublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdGet200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_public_subscription_api(
        self,
        subscription_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        view_id: typing.Optional[str] = OMIT,
        form_view_id: typing.Optional[str] = OMIT,
        properties: typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope]:
        """
        Parameters
        ----------
        subscription_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        view_id : typing.Optional[str]

        form_view_id : typing.Optional[str]

        properties : typing.Optional[typing.Dict[str, typing.Optional[typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/subscriptions/{jsonable_encoder(subscription_id)}",
            method="PUT",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            json={
                "view_id": view_id,
                "form_view_id": form_view_id,
                "properties": properties,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope,
                    construct_type(
                        type_=UpdatePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdPut200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_public_subscription_api(
        self,
        subscription_id: str,
        *,
        external_id: typing.Optional[str] = None,
        workspace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope]:
        """
        Parameters
        ----------
        subscription_id : str

        external_id : typing.Optional[str]

        workspace_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/public/subscriptions/{jsonable_encoder(subscription_id)}",
            method="DELETE",
            params={
                "external_id": external_id,
                "workspace_id": workspace_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope,
                    construct_type(
                        type_=DeletePublicSubscriptionApiV2PublicSubscriptionsSubscriptionIdDelete200Envelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorEnvelope,
                        construct_type(
                            type_=ErrorEnvelope,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
